"""systemd units generated from the jobs, and keeping them in step with them.

The jobs are the source of truth; the units are derived from them. When several
installs share one jobs.json (two operating systems on one machine, say), each
generates its own units — ``mirror-backup sync-units`` runs at every login and
brings them in line with whatever the other install changed meanwhile.

Two scopes (see ``paths``): user jobs become units of the user's service
manager, generated by the user; system jobs become system units, generated by
root from the installed copy in /etc/mirror-backup (``mirror-backup system
apply``). A job that names ``hosts`` gets units only on those hosts.

Only units carrying ``MARKER`` are considered ours to remove. A unit that is
replaced or removed goes to the trash, never straight to oblivion: it may hold
a hand edit that nobody carried back into jobs.json.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from backup_monitor import paths
from backup_monitor.fsutil import atomic_write_text, trash

MARKER = '# Generated by Mirror Backup from jobs.json — edit the job, not this file.'
UNIT_GLOBS = ('backup-*.service', 'backup-*.timer')

# rsync option → environment variable read by backup-sync
_BOOL_FLAGS = (
    ('compress', 'BACKUP_SYNC_COMPRESS'),
    ('checksum', 'BACKUP_SYNC_CHECKSUM'),
    ('hard_links', 'BACKUP_SYNC_HARD_LINKS'),
    ('xattrs', 'BACKUP_SYNC_XATTRS'),
    ('acls', 'BACKUP_SYNC_ACLS'),
    ('partial', 'BACKUP_SYNC_PARTIAL'),
    ('update', 'BACKUP_SYNC_UPDATE'),
)

Systemctl = Callable[[list[str]], subprocess.CompletedProcess]

# restic retention option → its --keep-* flag, in the order they are written
_KEEP_FLAGS = ('last', 'hourly', 'daily', 'weekly', 'monthly', 'yearly')


def systemctl(args: list[str], scope: str = 'user') -> subprocess.CompletedProcess:
    return subprocess.run(['systemctl', f'--{scope}', *args],
                          capture_output=True, text=True, timeout=30)


def scoped_systemctl(scope: str) -> Systemctl:
    return lambda args: systemctl(args, scope)


# ── rendering ──

def _specifier_safe(text: str) -> str:
    """Text for a unit setting where % introduces a specifier."""
    return text.replace('%', '%%')


def _exec_arg(arg: str) -> str:
    """One ExecStart argument, quoted: survives spaces, quotes, % and $."""
    s = str(arg).replace('\\', '\\\\').replace('"', '\\"')
    s = s.replace('%', '%%').replace('$', '$$')
    return f'"{s}"'


def _environment(name: str, value) -> str:
    v = str(value).replace('\\', '\\\\').replace('"', '\\"').replace('%', '%%')
    return f'Environment="{name}={v}"'


def timer_wanted(job: dict) -> bool:
    return job.get('schedule', {}).get('type', 'calendar') != 'manual'


def timer_enabled(job: dict) -> bool:
    return timer_wanted(job) and job.get('enabled', True)


def job_scope(job: dict) -> str:
    return 'system' if job.get('scope') == 'system' else 'user'


def job_engine(job: dict) -> str:
    return 'restic' if job.get('engine') == 'restic' else 'rsync'


def runs_here(job: dict, host: str | None = None) -> bool:
    """A job that lists ``hosts`` runs only on those; one that does not, everywhere."""
    hosts = job.get('hosts') or []
    return not hosts or (host or paths.host_name()) in hosts


def restic_keep_args(keep: dict) -> list[str]:
    """{'daily': 7, 'weekly': 4} → ['--keep-daily', '7', '--keep-weekly', '4']."""
    args = []
    for key in _KEEP_FLAGS:
        value = int((keep or {}).get(key, 0) or 0)
        if value > 0:
            args += [f'--keep-{key}', str(value)]
    return args


def resolve_job_file(job: dict, name: str) -> str:
    """A file a job names (exclude file), relative to its scope's config dir."""
    if not name:
        return ''
    if job_scope(job) == 'system':
        return name if name.startswith('/') else str(paths.system_config_dir() / name)
    return paths.resolve_config_path(name)


def restic_source(job: dict, jobs: list[dict]) -> str:
    """What backup-sync gets as <src> for a restic job: the generated path
    list (mode backup), or the destination of the job it copies from."""
    restic = job.get('restic') or {}
    if restic.get('mode', 'backup') == 'copy':
        source = next((j for j in jobs if j['id'] == restic.get('from_job')), None)
        return source['destination'] if source else ''
    return str(paths.generated_dir(job_scope(job)) / f'{job["id"]}.paths')


def render_paths_file(job: dict) -> str:
    return '\n'.join([MARKER, *(job.get('restic') or {}).get('paths', [])]) + '\n'


def _restic_environment(job: dict, jobs: list[dict]) -> list[str]:
    restic = job.get('restic') or {}
    mode = restic.get('mode', 'backup')
    env = [_environment('BACKUP_SYNC_ENGINE', 'restic'),
           _environment('BACKUP_SYNC_RESTIC_MODE', mode)]
    if restic.get('host'):
        env.append(_environment('BACKUP_SYNC_RESTIC_HOST', restic['host']))
    keep = restic_keep_args(restic.get('keep', {}))
    if keep:
        env.append(_environment('BACKUP_SYNC_RESTIC_KEEP', ' '.join(keep)))
    for key, name, default in (('prune_every_days', 'BACKUP_SYNC_RESTIC_PRUNE_DAYS', 7),
                               ('check_every_days', 'BACKUP_SYNC_RESTIC_CHECK_DAYS', 7)):
        env.append(_environment(name, int(restic.get(key, default) or 0)))
    env.append(_environment('BACKUP_SYNC_RESTIC_CHECK_SUBSET', restic.get('check_subset') or '5%'))
    if restic.get('password_file'):
        env.append(_environment('RESTIC_PASSWORD_FILE', restic['password_file']))
    if mode == 'copy':
        source = next((j for j in jobs if j['id'] == restic.get('from_job')), None)
        from_key = ((source or {}).get('restic') or {}).get('password_file')
        if from_key:
            env.append(_environment('RESTIC_FROM_PASSWORD_FILE', from_key))
    return env


def _rsync_environment(job: dict) -> list[str]:
    env = []
    bwlimit = int(job.get('bandwidth_limit_kbps', 0) or 0)
    if bwlimit > 0:
        env.append(_environment('BACKUP_SYNC_BWLIMIT', bwlimit))
    rsync_opts = job.get('rsync_options', {}) or {}
    for key, name in _BOOL_FLAGS:
        if rsync_opts.get(key, False):
            env.append(_environment(name, 1))
    delete_mode = rsync_opts.get('delete_mode', 'before')
    if delete_mode != 'before':
        env.append(_environment('BACKUP_SYNC_DELETE_MODE', delete_mode))
    for key, name in (('max_size', 'BACKUP_SYNC_MAX_SIZE'), ('min_size', 'BACKUP_SYNC_MIN_SIZE')):
        if rsync_opts.get(key):
            env.append(_environment(name, rsync_opts[key]))
    return env


# A system job runs as root and reads everything; what it may change is kept
# to its destination, its cache and state dirs, and the notification it sends.
# Only settings that make things read-only or private belong here — never one
# that *hides* a path a backup reads. ProtectKernelModules=yes, for one, mounts
# an empty, inaccessible directory over /usr/lib/modules: the first system
# snapshot came out without kernel modules, and its restore did not boot.
# ProtectHome, InaccessiblePaths and TemporaryFileSystem would do the same.
_SYSTEM_SANDBOX = (
    'CacheDirectory=mirror-backup',
    'StateDirectory=mirror-backup',
    'ProtectSystem=full',          # /usr, /boot, /etc read-only — still readable
    'PrivateTmp=yes',              # /tmp and /var/tmp: tmpfs or excluded anyway
    'NoNewPrivileges=yes',
    'ProtectKernelTunables=yes',   # /proc/sys, /sys read-only (other file systems)
    'ProtectControlGroups=yes',
    'RestrictRealtime=yes',
    'LockPersonality=yes',
)
# Settings that would hide data from a backup (see above).
HIDING_SETTINGS = ('ProtectKernelModules', 'ProtectHome', 'InaccessiblePaths',
                   'TemporaryFileSystem', 'ProtectKernelLogs', 'ProtectProc')


def render_service(job: dict, jobs: list[dict] | None = None, *, owner: str = '') -> str:
    """The job's service unit. ``jobs`` (all jobs of its scope) resolve the
    job a restic copy reads from and the jobs started after this one;
    ``owner`` is the user a system job reports to."""
    jobs = jobs if jobs is not None else [job]
    scope, engine = job_scope(job), job_engine(job)
    env = []
    if scope == 'system':
        env.append(_environment('BACKUP_SYNC_SCOPE', 'system'))
        if owner:
            env.append(_environment('BACKUP_SYNC_NOTIFY_USER', owner))
    if engine == 'restic':
        env += _restic_environment(job, jobs)
        source = restic_source(job, jobs)
    else:
        env += _rsync_environment(job)
        source = job['source']
    if job.get('pre_command'):
        env.append(_environment('BACKUP_SYNC_PRE_COMMAND', pre_command_path(job)))

    exclude = resolve_job_file(job, job.get('exclude_file', '') or '')
    args = ' '.join(_exec_arg(a) for a in (
        job['id'], source, job['destination'], exclude,
        int(job.get('archive_days', 0) or 0),
    ))
    program = (f'{paths.SYSTEM_LIB_DIR}/backup-sync' if scope == 'system'
               else '%h/.local/bin/backup-sync')
    desc = _specifier_safe(job.get('description') or f'Backup {job["name"]}')
    followers = sorted(f'{j["id"]}.service' for j in jobs
                       if j.get('run_after') == job['id'] and j['id'] != job['id'])
    lines = [
        MARKER,
        '[Unit]',
        f'Description={desc}',
        *([f'OnSuccess={" ".join(followers)}'] if followers else []),
        '',
        '[Service]',
        'Type=simple',
        *env,
        f'ExecStart={program} {args}',
        'KillSignal=SIGTERM',
        'KillMode=mixed',
        'TimeoutStopSec=30',
        f'Nice={int(job.get("nice", 10))}',
        'IOSchedulingClass=best-effort',
        f'IOSchedulingPriority={int(job.get("io_priority", 7))}',
        *(_SYSTEM_SANDBOX if scope == 'system' else ()),
        '',
    ]
    return '\n'.join(lines) + '\n'


def pre_command_path(job: dict) -> str:
    """A system job's pre-command is the name of a program Mirror Backup ships
    (paths.SYSTEM_LIB_DIR); root never runs anything a user could have changed.
    A user job's is a path of its own choosing."""
    name = job.get('pre_command', '') or ''
    if job_scope(job) == 'system':
        return f'{paths.SYSTEM_LIB_DIR}/{name}'
    return paths.resolve_config_path(name) if name and '/' in name else name


def render_timer(job: dict) -> str:
    desc = _specifier_safe(job.get('description') or f'Backup {job["name"]}')
    expression = job.get('schedule', {}).get('expression', 'daily')
    return '\n'.join([
        MARKER,
        '[Unit]',
        f'Description={desc} (timer)',
        '',
        '[Timer]',
        f'OnCalendar={expression}',
        'Persistent=true',
        '',
        '[Install]',
        'WantedBy=timers.target',
        '',
    ])


def desired_units(jobs: list[dict], *, owner: str = '') -> dict[str, str]:
    units = {}
    for job in jobs:
        units[f'{job["id"]}.service'] = render_service(job, jobs, owner=owner)
        if timer_wanted(job):
            units[f'{job["id"]}.timer'] = render_timer(job)
    return units


def desired_files(jobs: list[dict]) -> dict[str, str]:
    """The path lists of restic backup jobs, by file name in the generated dir."""
    return {f'{j["id"]}.paths': render_paths_file(j) for j in jobs
            if job_engine(j) == 'restic' and (j.get('restic') or {}).get('mode', 'backup') == 'backup'}


# ── reconciling ──

@dataclass
class SyncReport:
    written: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    enabled: list[str] = field(default_factory=list)
    disabled: list[str] = field(default_factory=list)
    unmanaged: list[str] = field(default_factory=list)   # backup-* units we did not generate
    errors: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed or self.enabled or self.disabled)

    def lines(self) -> list[str]:
        out = []
        for label, items in (('wrote', self.written), ('removed', self.removed),
                             ('enabled', self.enabled), ('disabled', self.disabled),
                             ('left alone (not generated by Mirror Backup)', self.unmanaged),
                             ('error', self.errors)):
            out.extend(f'{label}: {item}' for item in items)
        return out


def is_generated(path: Path) -> bool:
    try:
        with open(path, encoding='utf-8') as f:
            return f.readline().rstrip('\n') == MARKER
    except (OSError, UnicodeDecodeError):
        return False


def sync_units(jobs: list[dict], *, scope: str = 'user', unit_dir: Path | None = None,
               generated_dir: Path | None = None, run: Systemctl | None = None,
               remove_ids: tuple[str, ...] = (), owner: str = '',
               discard: Callable[[Path], str] = trash, host: str | None = None) -> SyncReport:
    """Make the backup units of ``scope`` match ``jobs``.

    Writes units whose content differs (the previous file to the trash first),
    removes generated units of jobs that no longer exist, and enables or
    disables timers to match each job. ``remove_ids`` also removes units of
    those job ids when they were not generated by us — a job the user just
    deleted in the app. ``discard`` disposes of replaced files (the trash).
    Jobs of the other scope, and jobs meant for other hosts, get no units.
    """
    unit_dir = unit_dir or paths.unit_dir(scope)
    generated_dir = generated_dir or paths.generated_dir(scope)
    run = run or scoped_systemctl(scope)
    unit_dir.mkdir(parents=True, exist_ok=True)
    report = SyncReport()
    invalid = [j.get('id') for j in jobs if not valid_job_id(str(j.get('id', '')))]
    report.errors.extend(f'invalid job id {i!r} — no units' for i in invalid)
    jobs = [j for j in jobs if j.get('id') not in invalid and job_scope(j) == scope]
    here = [j for j in jobs if runs_here(j, host)]
    desired = desired_units(here, owner=owner)

    files = desired_files(here)
    if files or generated_dir.is_dir():
        generated_dir.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            path = generated_dir / name
            try:
                if path.read_text(encoding='utf-8') == content:
                    continue
            except (OSError, UnicodeDecodeError):
                pass
            atomic_write_text(path, content, mode=0o644)
        for path in sorted(generated_dir.glob('*.paths')):
            if path.name not in files and is_generated(path):
                discard(path)
    jobs = here

    for name, content in desired.items():
        path = unit_dir / name
        try:
            current = path.read_text(encoding='utf-8')
        except FileNotFoundError:
            current = None
        except (OSError, UnicodeDecodeError):
            current = ''
        if current == content:
            continue
        if current is not None:
            discard(path)
        atomic_write_text(path, content, mode=0o644)
        report.written.append(name)

    existing = sorted({p for g in UNIT_GLOBS for p in unit_dir.glob(g)})
    for path in existing:
        if path.name in desired:
            continue
        job_id = path.name.rsplit('.', 1)[0]
        if not is_generated(path) and job_id not in remove_ids:
            report.unmanaged.append(path.name)
            continue
        if path.suffix == '.timer':
            run(['disable', '--now', path.name])
        else:
            run(['stop', path.name])
        discard(path)
        report.removed.append(path.name)

    if report.written or report.removed:
        result = run(['daemon-reload'])
        if result.returncode != 0:
            report.errors.append(f'daemon-reload: {result.stderr.strip()}')

    for job in jobs:
        timer = f'{job["id"]}.timer'
        if not timer_wanted(job):
            continue
        want = timer_enabled(job)
        state = run(['is-enabled', timer]).stdout.strip()
        active = run(['is-active', timer]).stdout.strip() == 'active'
        if want and (state != 'enabled' or not active):
            result = run(['enable', '--now', timer])
            (report.enabled if result.returncode == 0 else report.errors).append(
                timer if result.returncode == 0 else f'enable {timer}: {result.stderr.strip()}')
        elif not want and (state == 'enabled' or active):
            result = run(['disable', '--now', timer])
            (report.disabled if result.returncode == 0 else report.errors).append(
                timer if result.returncode == 0 else f'disable {timer}: {result.stderr.strip()}')
    return report


_JOB_ID = re.compile(r'^backup-[a-z0-9][a-z0-9-]*$')


def valid_job_id(job_id: str) -> bool:
    return bool(_JOB_ID.match(job_id))
