"""systemd user units generated from jobs.json, and keeping them in step with it.

jobs.json is the source of truth; the units are derived from it. When several
installs share one jobs.json (two operating systems on one machine, say), each
generates its own units — ``mirror-backup sync-units`` runs at every login and
brings them in line with whatever the other install changed meanwhile.

Only units carrying ``MARKER`` are considered ours to remove. A unit that is
replaced or removed goes to the trash, never straight to oblivion: it may hold
a hand edit that nobody carried back into jobs.json.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

from backup_monitor import paths
from backup_monitor.fsutil import atomic_write_text, trash

MARKER = '# Generated by Mirror Backup from jobs.json — edit the job, not this file.'
UNIT_GLOBS = ('backup-*.service', 'backup-*.timer')

# rsync option → environment variable read by backup-sync
_BOOL_FLAGS = (
    ('compress', 'BACKUP_SYNC_COMPRESS'),
    ('checksum', 'BACKUP_SYNC_CHECKSUM'),
    ('hard_links', 'BACKUP_SYNC_HARD_LINKS'),
    ('xattrs', 'BACKUP_SYNC_XATTRS'),
    ('acls', 'BACKUP_SYNC_ACLS'),
    ('partial', 'BACKUP_SYNC_PARTIAL'),
    ('update', 'BACKUP_SYNC_UPDATE'),
)

Systemctl = Callable[[list[str]], subprocess.CompletedProcess]


def systemctl(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(['systemctl', '--user', *args],
                          capture_output=True, text=True, timeout=30)


# ── rendering ──

def _specifier_safe(text: str) -> str:
    """Text for a unit setting where % introduces a specifier."""
    return text.replace('%', '%%')


def _exec_arg(arg: str) -> str:
    """One ExecStart argument, quoted: survives spaces, quotes, % and $."""
    s = str(arg).replace('\\', '\\\\').replace('"', '\\"')
    s = s.replace('%', '%%').replace('$', '$$')
    return f'"{s}"'


def _environment(name: str, value) -> str:
    v = str(value).replace('\\', '\\\\').replace('"', '\\"').replace('%', '%%')
    return f'Environment="{name}={v}"'


def timer_wanted(job: dict) -> bool:
    return job.get('schedule', {}).get('type', 'calendar') != 'manual'


def timer_enabled(job: dict) -> bool:
    return timer_wanted(job) and job.get('enabled', True)


def render_service(job: dict) -> str:
    env = []
    bwlimit = int(job.get('bandwidth_limit_kbps', 0) or 0)
    if bwlimit > 0:
        env.append(_environment('BACKUP_SYNC_BWLIMIT', bwlimit))
    rsync_opts = job.get('rsync_options', {}) or {}
    for key, name in _BOOL_FLAGS:
        if rsync_opts.get(key, False):
            env.append(_environment(name, 1))
    delete_mode = rsync_opts.get('delete_mode', 'before')
    if delete_mode != 'before':
        env.append(_environment('BACKUP_SYNC_DELETE_MODE', delete_mode))
    for key, name in (('max_size', 'BACKUP_SYNC_MAX_SIZE'), ('min_size', 'BACKUP_SYNC_MIN_SIZE')):
        if rsync_opts.get(key):
            env.append(_environment(name, rsync_opts[key]))

    exclude = paths.resolve_config_path(job.get('exclude_file', '') or '')
    args = ' '.join(_exec_arg(a) for a in (
        job['id'], job['source'], job['destination'], exclude,
        int(job.get('archive_days', 0) or 0),
    ))
    desc = _specifier_safe(job.get('description') or f'Backup {job["name"]}')
    lines = [
        MARKER,
        '[Unit]',
        f'Description={desc}',
        '',
        '[Service]',
        'Type=simple',
        *env,
        f'ExecStart=%h/.local/bin/backup-sync {args}',
        'KillSignal=SIGTERM',
        'KillMode=mixed',
        'TimeoutStopSec=30',
        f'Nice={int(job.get("nice", 10))}',
        'IOSchedulingClass=best-effort',
        f'IOSchedulingPriority={int(job.get("io_priority", 7))}',
        '',
    ]
    return '\n'.join(lines) + '\n'


def render_timer(job: dict) -> str:
    desc = _specifier_safe(job.get('description') or f'Backup {job["name"]}')
    expression = job.get('schedule', {}).get('expression', 'daily')
    return '\n'.join([
        MARKER,
        '[Unit]',
        f'Description={desc} (timer)',
        '',
        '[Timer]',
        f'OnCalendar={expression}',
        'Persistent=true',
        '',
        '[Install]',
        'WantedBy=timers.target',
        '',
    ])


def desired_units(jobs: list[dict]) -> dict[str, str]:
    units = {}
    for job in jobs:
        units[f'{job["id"]}.service'] = render_service(job)
        if timer_wanted(job):
            units[f'{job["id"]}.timer'] = render_timer(job)
    return units


# ── reconciling ──

@dataclass
class SyncReport:
    written: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    enabled: list[str] = field(default_factory=list)
    disabled: list[str] = field(default_factory=list)
    unmanaged: list[str] = field(default_factory=list)   # backup-* units we did not generate
    errors: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed or self.enabled or self.disabled)

    def lines(self) -> list[str]:
        out = []
        for label, items in (('wrote', self.written), ('removed', self.removed),
                             ('enabled', self.enabled), ('disabled', self.disabled),
                             ('left alone (not generated by Mirror Backup)', self.unmanaged),
                             ('error', self.errors)):
            out.extend(f'{label}: {item}' for item in items)
        return out


def is_generated(path: Path) -> bool:
    try:
        with open(path, encoding='utf-8') as f:
            return f.readline().rstrip('\n') == MARKER
    except (OSError, UnicodeDecodeError):
        return False


def sync_units(jobs: list[dict], *, unit_dir: Path | None = None,
               run: Systemctl = systemctl, remove_ids: tuple[str, ...] = (),
               discard: Callable[[Path], str] = trash) -> SyncReport:
    """Make the backup units match ``jobs``.

    Writes units whose content differs (the previous file to the trash first),
    removes generated units of jobs that no longer exist, and enables or
    disables timers to match each job. ``remove_ids`` also removes units of
    those job ids when they were not generated by us — a job the user just
    deleted in the app. ``discard`` disposes of replaced files (the trash).
    """
    unit_dir = unit_dir or paths.systemd_user_dir()
    unit_dir.mkdir(parents=True, exist_ok=True)
    report = SyncReport()
    invalid = [j.get('id') for j in jobs if not valid_job_id(str(j.get('id', '')))]
    report.errors.extend(f'invalid job id {i!r} — no units' for i in invalid)
    jobs = [j for j in jobs if j.get('id') not in invalid]
    desired = desired_units(jobs)

    for name, content in desired.items():
        path = unit_dir / name
        try:
            current = path.read_text(encoding='utf-8')
        except FileNotFoundError:
            current = None
        except (OSError, UnicodeDecodeError):
            current = ''
        if current == content:
            continue
        if current is not None:
            discard(path)
        atomic_write_text(path, content, mode=0o644)
        report.written.append(name)

    existing = sorted({p for g in UNIT_GLOBS for p in unit_dir.glob(g)})
    for path in existing:
        if path.name in desired:
            continue
        job_id = path.name.rsplit('.', 1)[0]
        if not is_generated(path) and job_id not in remove_ids:
            report.unmanaged.append(path.name)
            continue
        if path.suffix == '.timer':
            run(['disable', '--now', path.name])
        else:
            run(['stop', path.name])
        discard(path)
        report.removed.append(path.name)

    if report.written or report.removed:
        result = run(['daemon-reload'])
        if result.returncode != 0:
            report.errors.append(f'daemon-reload: {result.stderr.strip()}')

    for job in jobs:
        timer = f'{job["id"]}.timer'
        if not timer_wanted(job):
            continue
        want = timer_enabled(job)
        state = run(['is-enabled', timer]).stdout.strip()
        active = run(['is-active', timer]).stdout.strip() == 'active'
        if want and (state != 'enabled' or not active):
            result = run(['enable', '--now', timer])
            (report.enabled if result.returncode == 0 else report.errors).append(
                timer if result.returncode == 0 else f'enable {timer}: {result.stderr.strip()}')
        elif not want and (state == 'enabled' or active):
            result = run(['disable', '--now', timer])
            (report.disabled if result.returncode == 0 else report.errors).append(
                timer if result.returncode == 0 else f'disable {timer}: {result.stderr.strip()}')
    return report


_JOB_ID = re.compile(r'^backup-[a-z0-9][a-z0-9-]*$')


def valid_job_id(job_id: str) -> bool:
    return bool(_JOB_ID.match(job_id))
