#!/usr/bin/env bash
# Uninstall Mirror Backup. Everything removed goes to the trash.
#
#   ./uninstall.sh [--system]
#
# Kept: the jobs (~/.config/backup-sync, or the overlay it links to) and each
# job's state in its destination (<destination>/.mirror-backup) — both are
# data, and other installs sharing them may still be using them.
#
# --system also removes the system part (with sudo): the system jobs' units,
# the root-owned copy in /usr/local/lib/mirror-backup, the shared queue, the
# polkit rule and the resume unit. /etc/mirror-backup stays — it holds the
# repository keys, without which the restic repositories cannot be opened.
set -euo pipefail

SYSTEM=0
[[ "${1:-}" == --system ]] && SYSTEM=1

EXT_UUID="backup-monitor@petronijus"
PLUGIN_ID="petronijus.mirror-backup"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
UNIT_DIR="$CONFIG_HOME/systemd/user"

trash() {
    [[ -e "$1" || -L "$1" ]] || return 0
    if command -v gio >/dev/null && gio trash -- "$1" 2>/dev/null; then return 0; fi
    if command -v trash-put >/dev/null && trash-put -- "$1"; then return 0; fi
    echo "  ! cannot move $1 to the trash — left in place" >&2
}

echo "=== Mirror Backup uninstaller ==="

echo "Stopping backup timers and runs..."
shopt -s nullglob
for unit in "$UNIT_DIR"/backup-*.timer "$UNIT_DIR"/backup-*.service; do
    systemctl --user disable --now "$(basename "$unit")" 2>/dev/null || true
done
systemctl --user disable mirror-backup-resume.service 2>/dev/null || true

echo "Removing systemd units..."
for unit in "$UNIT_DIR"/backup-*.service "$UNIT_DIR"/backup-*.timer "$UNIT_DIR"/backup-*.timer.d \
            "$UNIT_DIR/mirror-backup-resume.service"; do
    trash "$unit"
done
systemctl --user daemon-reload

echo "Removing panels..."
gnome-extensions disable "$EXT_UUID" 2>/dev/null || true
trash "$DATA_HOME/gnome-shell/extensions/$EXT_UUID"
if command -v omarchy >/dev/null; then
    omarchy plugin disable "$PLUGIN_ID" >/dev/null 2>&1 || true
fi
trash "$CONFIG_HOME/omarchy/plugins/$PLUGIN_ID"

echo "Removing the app and commands..."
trash "$DATA_HOME/mirror-backup"
trash "$DATA_HOME/applications/com.github.petronijus.BackupMonitor.desktop"
trash "$HOME/.local/bin/backup-sync"
trash "$HOME/.local/bin/mirror-backup"

if (( SYSTEM )); then
    echo "Removing the system part..."
    AS_ROOT=()
    (( EUID == 0 )) || AS_ROOT=(sudo)
    MARKER='# Generated by Mirror Backup from jobs.json — edit the job, not this file.'
    for unit in /etc/systemd/system/*.timer /etc/systemd/system/*.service \
                /etc/systemd/system/*.automount /etc/systemd/system/*.mount; do
        [[ -f "$unit" && "$(head -n 1 "$unit")" == "$MARKER" ]] || continue
        "${AS_ROOT[@]}" systemctl disable --now "$(basename "$unit")" 2>/dev/null || true
        "${AS_ROOT[@]}" gio trash -- "$unit" 2>/dev/null || echo "  ! $unit left in place" >&2
    done
    "${AS_ROOT[@]}" systemctl disable mirror-backup-resume-system.service 2>/dev/null || true
    for f in /etc/systemd/system/mirror-backup-resume-system.service /etc/tmpfiles.d/mirror-backup.conf \
             /etc/polkit-1/rules.d/50-mirror-backup.rules /usr/local/lib/mirror-backup \
             /etc/mirror-backup/generated; do
        "${AS_ROOT[@]}" test -e "$f" || continue
        "${AS_ROOT[@]}" gio trash -- "$f" 2>/dev/null || echo "  ! $f left in place" >&2
    done
    "${AS_ROOT[@]}" systemctl daemon-reload
    echo "Kept: /etc/mirror-backup (system jobs and repository keys)."
fi

echo ""
echo "=== Uninstalled ==="
echo "Kept: $CONFIG_HOME/backup-sync (jobs) and <destination>/.mirror-backup (job state)."
